// Package schemas provides the JSON schemas embedded into the nelm binary, so that resources can be
// validated without network access. The archives are committed rather than built, so that importing
// nelm as a library gets them too; they are regenerated by scripts/schemagen, see data/README.md.
package schemas

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
)

const (
	crdsArchiveFileName = "data/crds.tar.gz"
	crdsBundleName      = "crds"
	// Both templates must mirror the layout of the archive they address, and must end in ".json", or
	// kubeconform takes the source for a directory and appends a layout of its own.
	crdsSchemaPathTemplate       = "{{ .Group }}/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json"
	indexFileName                = "data/index.json"
	kubernetesArchiveFileName    = "data/kubernetes.tar.gz"
	kubernetesBundleName         = "kubernetes"
	kubernetesSchemaPathTemplate = "{{ .ResourceKind }}{{ .KindSuffix }}.json"
	sha256HexLen                 = 64
)

var (
	// Named one by one rather than by glob: the patterns failing the build on a missing archive is what
	// makes a binary without embedded schemas impossible to produce.
	//go:embed data/index.json
	//go:embed data/crds.tar.gz
	//go:embed data/kubernetes.tar.gz
	data embed.FS

	// Whatever the build cannot enforce about the index is checked here, once. It describes files that
	// are part of the binary image, so anything wrong with it is a defect of this repository.
	readIndex = sync.OnceValues(func() (*Index, error) {
		indexBytes, err := data.ReadFile(indexFileName)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", indexFileName, err)
		}

		var index Index

		if err := json.Unmarshal(indexBytes, &index); err != nil {
			return nil, fmt.Errorf("decode %s: %w", indexFileName, err)
		}

		if err := index.validate(); err != nil {
			return nil, fmt.Errorf("invalid %s, regenerate it with: task generate:validation-schemas: %w", indexFileName, err)
		}

		return &index, nil
	})
)

// Bundle describes one embedded archive. It is generated alongside the archive itself.
type Bundle struct {
	FilesCount int `json:"filesCount"`
	// KubeVersions are ordered newest first, and only set for the Kubernetes bundle.
	KubeVersions     []string `json:"kubeVersions,omitempty"`
	SHA256           string   `json:"sha256"`
	UncompressedSize int64    `json:"uncompressedSize"`
	UpstreamCommit   string   `json:"upstreamCommit"`
	UpstreamRef      string   `json:"upstreamRef"`
	UpstreamRepo     string   `json:"upstreamRepo"`
	// UpstreamTrees maps each collected Kubernetes version to the git tree sha of the upstream
	// directory its schemas came from, which is what tells a moved ref that changed those schemas from
	// one that did not. Only set for the Kubernetes bundle.
	UpstreamTrees map[string]string `json:"upstreamTrees,omitempty"`
}

func (b *Bundle) validate() error {
	if len(b.SHA256) != sha256HexLen {
		return fmt.Errorf("invalid sha256 %q", b.SHA256)
	}

	if b.FilesCount < 1 {
		return errors.New("no embedded validation schemas found")
	}

	return nil
}

// Index describes the bundles embedded into this binary. Both are always present: a binary that
// cannot validate resources on its own is not a supported build.
type Index struct {
	CRDs *Bundle `json:"crds"`
	// Kubernetes holds several minor versions merged into one flat set: the newest contributes all of
	// its schemas, every older one only what no newer version has any more, which is what keeps
	// resources of API versions removed along the way validatable.
	Kubernetes *Bundle `json:"kubernetes"`
}

func (i *Index) validate() error {
	if i.Kubernetes == nil {
		return errors.New("no kubernetes bundle")
	}

	if err := i.Kubernetes.validate(); err != nil {
		return fmt.Errorf("kubernetes bundle: %w", err)
	}

	if len(i.Kubernetes.KubeVersions) == 0 {
		return errors.New("kubernetes bundle: no kube versions recorded")
	}

	for _, kubeVersion := range i.Kubernetes.KubeVersions {
		if !isKubeVersion(kubeVersion) {
			return fmt.Errorf("kubernetes bundle: invalid kube version %q", kubeVersion)
		}
	}

	if i.CRDs == nil {
		return errors.New("no crds bundle")
	}

	if err := i.CRDs.validate(); err != nil {
		return fmt.Errorf("crds bundle: %w", err)
	}

	return nil
}

// Source is a kubeconform schema source backed by an embedded bundle.
type Source struct {
	// Template is a kubeconform schema source: a path template into the unpacked bundle.
	Template string

	bundle *embeddedBundle
}

// EnsureExtracted unpacks the bundle backing this source. Callers must do this before reading it.
func (s *Source) EnsureExtracted(ctx context.Context) error {
	_, err := s.bundle.ensureExtracted(ctx)

	return err
}

func (b *embeddedBundle) source() *Source {
	return &Source{
		Template: filepath.Join(b.extractionDir(), filepath.FromSlash(b.schemaPathTemplate)),
		bundle:   b,
	}
}

// KubeVersion returns the Kubernetes version resources are validated against: the newest the embedded
// schemas were collected from, pinned when they are generated.
func KubeVersion() (string, error) {
	kubeVersions, err := KubeVersions()
	if err != nil {
		return "", err
	}

	return kubeVersions[0], nil
}

// CRDsSource returns the schema source backed by the embedded CRD catalog.
func CRDsSource() (*Source, error) {
	index, err := ReadIndex()
	if err != nil {
		return nil, err
	}

	return newBundle(crdsBundleName, crdsArchiveFileName, crdsSchemaPathTemplate, crdsMaxPathDepth, index.CRDs).source(), nil
}

// KubeVersions returns the Kubernetes versions the embedded schemas were collected from, newest first.
func KubeVersions() ([]string, error) {
	index, err := ReadIndex()
	if err != nil {
		return nil, err
	}

	return slices.Clone(index.Kubernetes.KubeVersions), nil
}

// KubernetesSource returns the schema source backed by the embedded Kubernetes schemas.
func KubernetesSource() (*Source, error) {
	index, err := ReadIndex()
	if err != nil {
		return nil, err
	}

	return newBundle(kubernetesBundleName, kubernetesArchiveFileName,
		kubernetesSchemaPathTemplate, kubernetesMaxPathDepth, index.Kubernetes).source(), nil
}

// ReadIndex returns the index of the embedded bundles.
func ReadIndex() (*Index, error) {
	return readIndex()
}

// liveExtractionDirNames are the directory names the stale extraction cleanup must not touch.
func liveExtractionDirNames() ([]string, error) {
	index, err := ReadIndex()
	if err != nil {
		return nil, err
	}

	return []string{
		extractionDirName(kubernetesBundleName, index.Kubernetes),
		extractionDirName(crdsBundleName, index.CRDs),
	}, nil
}

func extractionDirName(name string, index *Bundle) string {
	return fmt.Sprintf("%s-%s", name, index.SHA256[:12])
}

// isKubeVersion reports whether the string is a numeric Kubernetes version, which is what the index
// must record. kubeconform's "master" is not one.
func isKubeVersion(kubeVersion string) bool {
	parts := strings.SplitN(strings.TrimPrefix(kubeVersion, "v"), ".", 3)
	if len(parts) < 2 {
		return false
	}

	for _, part := range parts[:2] {
		if _, err := strconv.Atoi(part); err != nil {
			return false
		}
	}

	return true
}
