// Package denolock provides the pinned Deno release nelm downloads and embeds. The digests are
// committed and embedded rather than fetched, so that they go through code review instead of coming
// from the same host as the artifact they are supposed to vouch for. Generated by scripts/denolock.
package denolock

import (
	"embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"slices"
	"strings"
	"sync"
)

const (
	// ChecksumURLSuffix is only for scripts/denolock: nothing verifies against a fetched digest.
	ChecksumURLSuffix = ".sha256sum"

	archiveURLTemplate = "https://github.com/denoland/deno/releases/download/v%s/deno-%s.zip"
	lockFileName       = "data/lock.json"
	sha256HexLen       = 64
)

var (
	//go:embed data/lock.json
	data embed.FS

	readLock = sync.OnceValues(func() (*Lock, error) {
		lockBytes, err := data.ReadFile(lockFileName)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", lockFileName, err)
		}

		var lock Lock

		if err := json.Unmarshal(lockBytes, &lock); err != nil {
			return nil, fmt.Errorf("decode %s: %w", lockFileName, err)
		}

		if err := lock.Validate(); err != nil {
			return nil, fmt.Errorf("invalid %s, regenerate it with: task deno:lock: %w", lockFileName, err)
		}

		return &lock, nil
	})
)

type Platform struct {
	ArchiveSHA256 string `json:"archiveSha256"`
	// BinarySHA256 is the digest of the uncompressed Deno binary inside the archive, which is what the
	// embedded blob is checked against.
	BinarySHA256 string `json:"binarySha256"`
	Target       string `json:"target"`
}

func (p *Platform) validate() error {
	if p.Target == "" {
		return errors.New("no target triple")
	}

	if err := validateSHA256(p.ArchiveSHA256); err != nil {
		return fmt.Errorf("archive sha256: %w", err)
	}

	if err := validateSHA256(p.BinarySHA256); err != nil {
		return fmt.Errorf("binary sha256: %w", err)
	}

	return nil
}

type Lock struct {
	// Platforms is keyed by "<GOOS>/<GOARCH>".
	Platforms map[string]*Platform `json:"platforms"`
	Version   string               `json:"version"`
}

func (l *Lock) ArchiveURL(goos, goarch string) (string, error) {
	entry, err := l.Get(goos, goarch)
	if err != nil {
		return "", err
	}

	return ArchiveURLFor(l.Version, entry.Target), nil
}

func (l *Lock) Get(goos, goarch string) (*Platform, error) {
	entry, found := l.Platforms[platformKey(goos, goarch)]
	if !found {
		return nil, fmt.Errorf("unsupported platform: %s/%s", goos, goarch)
	}

	return entry, nil
}

func (l *Lock) Validate() error {
	if l.Version == "" {
		return errors.New("no version")
	}

	if strings.HasPrefix(l.Version, "v") {
		return fmt.Errorf("version %q must be recorded without the leading \"v\"", l.Version)
	}

	if len(l.Platforms) == 0 {
		return errors.New("no platforms")
	}

	for _, platform := range slices.Sorted(maps.Keys(l.Platforms)) {
		goos, goarch, found := strings.Cut(platform, "/")
		if !found || goos == "" || goarch == "" {
			return fmt.Errorf("platform key %q is not \"<os>/<arch>\"", platform)
		}

		entry := l.Platforms[platform]
		if entry == nil {
			return fmt.Errorf("platform %s: no entry", platform)
		}

		if err := entry.validate(); err != nil {
			return fmt.Errorf("platform %s: %w", platform, err)
		}
	}

	return nil
}

func ArchiveURL(goos, goarch string) (string, error) {
	lock, err := Read()
	if err != nil {
		return "", err
	}

	return lock.ArchiveURL(goos, goarch)
}

func Get(goos, goarch string) (*Platform, error) {
	lock, err := Read()
	if err != nil {
		return nil, err
	}

	return lock.Get(goos, goarch)
}

func Version() (string, error) {
	lock, err := Read()
	if err != nil {
		return "", err
	}

	return lock.Version, nil
}

// ArchiveURLFor is for scripts/denolock, which builds URLs for a version the lock does not record yet.
func ArchiveURLFor(version, target string) string {
	return fmt.Sprintf(archiveURLTemplate, strings.TrimPrefix(version, "v"), target)
}

func Read() (*Lock, error) {
	return readLock()
}

func platformKey(goos, goarch string) string {
	return goos + "/" + goarch
}

func validateSHA256(digest string) error {
	if len(digest) != sha256HexLen {
		return fmt.Errorf("%q is not %d hex characters", digest, sha256HexLen)
	}

	if digest != strings.ToLower(digest) {
		return fmt.Errorf("%q must be lowercase", digest)
	}

	if _, err := hex.DecodeString(digest); err != nil {
		return fmt.Errorf("%q is not hex: %w", digest, err)
	}

	return nil
}
