name: xxxxx(internal)

on:
  workflow_call:
    inputs:
      forceSkip:
        default: false
        type: string

defaults:
  run:
    shell: bash

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  _:
    if: inputs.forceSkip == 'false'
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          cache: false
          go-version-file: go.mod

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install golangci-lint
        run: task -p deps:install:golangci-lint

      - name: Lint
        run: task -p lint
