name: generate:main

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TASK_X_REMOTE_TASKFILES: "1"

jobs:
  generate-reference:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          cache: false
          go-version-file: go.mod

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa
        with:
          repo-token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Generate reference docs
        run: task generate:reference

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet docs/reference.md || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Set up git config
        if: steps.changes.outputs.changed == 'true'
        uses: ./.github/actions/set-up-git-config

      - name: Commit and push
        if: steps.changes.outputs.changed == 'true'
        run: |
          git add docs/reference.md
          git commit -m "chore: regenerate CLI reference"
          git push
